default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.6.2
    hooks:
      - id: pydocstringformatter
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: [--py310-plus]
      - id: nbqa-isort
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.0
    hooks:
    - id: jupytext
      args: [--sync, --pipe, black]
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.4
  #   hooks:
  #     - id: bandit
